imagePullSecrets:
- name: ghcr-pull-secret
services:
  auth:
    image:
      repository: ghcr.io/byron-movie-cloud/auth-service
      tag: b0f2bfeafe537d8695b62d2813939599de9646ad
  movie:
    image:
      repository: ghcr.io/byron-movie-cloud/movie-service
      tag: latest
  user:
    image:
      repository: ghcr.io/byron-movie-cloud/user-service
      tag: acac60b4bff749e9451679e3d45df97da6e10a41
  frontend:
    image:
      repository: ghcr.io/byron-movie-cloud/frontend
      tag: a785290ddf85894495d10cd79ae832437f7cffb1
ingress:
  enabled: true
  className: nginx
  host: movies.example.com
